"""add session name to treatment session

Revision ID: 0984d45fd884
Revises: c4d3be2c4a8e
Create Date: 2025-11-14 17:51:36.998448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0984d45fd884'
down_revision = 'c4d3be2c4a8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_session', sa.Column('session_name', sa.String(length=255), nullable=True, comment='세션 이름'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_session', 'session_name')
    # ### end Alembic commands ###

