"""Initial migration

Revision ID: 3e93f2a629b2
Revises: 
Create Date: 2025-10-22 00:21:42.783723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '3e93f2a629b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True, comment='상호명'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='주소'),
    sa.Column('owner_name', sa.String(length=255), nullable=True, comment='대표자명'),
    sa.Column('phone', sa.String(length=255), nullable=True, comment='전화번호'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='이메일 (로그인 ID)'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='비밀번호 (암호화 저장)'),
    sa.Column('refresh_token', sa.String(length=255), nullable=True, comment='현재 로그인 중인 Refresh Token 저장'),
    sa.Column('refresh_token_expiry', sa.DateTime(), nullable=True, comment='Refresh Token 만료 일시'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='마지막 로그인 시간 (선택)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop'))
    )
    op.create_index(op.f('ix_shop_id'), 'shop', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('customer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True, comment='고객명'),
    sa.Column('age', sa.Integer(), nullable=True, comment='나이'),
    sa.Column('gender', sa.Enum('M', 'F', name='gender_enum', create_type=False), nullable=True, comment='성별 (M/F)'),
    sa.Column('phone', sa.String(length=255), nullable=True, comment='연락처'),
    sa.Column('skin_type', sa.String(length=255), nullable=True, comment='피부타입'),
    sa.Column('note', sa.Text(), nullable=True, comment='특이사항'),
    sa.Column('marked', sa.SmallInteger(), nullable=True, comment='상단 고정 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name=op.f('fk_customer_shop_id_shop')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_items_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_tokens'))
    )
    op.create_index(op.f('ix_user_tokens_expires_at'), 'user_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_tokens_id'), 'user_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_tokens_session_id'), 'user_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_tokens_token_hash'), 'user_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    op.create_table('treatment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True, comment='시술 종류 (튼살-경, 튼살-중, 백반증, 흉터 등)'),
    sa.Column('area', sa.String(length=255), nullable=True, comment='시술 부위 (얼굴, 목, 팔, 다리, 입술 등)'),
    sa.Column('is_completed', sa.Boolean(), nullable=True, comment='시술 완료 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_treatment_customer_id_customer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatment'))
    )
    op.create_index(op.f('ix_treatment_id'), 'treatment', ['id'], unique=False)
    op.create_table('treatment_session',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('treatment_id', sa.BigInteger(), nullable=False),
    sa.Column('treatment_date', sa.Date(), nullable=True, comment='시술 날짜'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='소요시간(분)'),
    sa.Column('melanin', sa.Integer(), nullable=True, comment='멜라닌 투입량 (0~9)'),
    sa.Column('white', sa.Integer(), nullable=True, comment='화이트 투입량 (0~9)'),
    sa.Column('red', sa.Integer(), nullable=True, comment='레드 투입량 (0~9)'),
    sa.Column('yellow', sa.Integer(), nullable=True, comment='옐로우 투입량 (0~9)'),
    sa.Column('is_completed', sa.Boolean(), nullable=True, comment='시술 완료 여부'),
    sa.Column('is_result_entered', sa.SmallInteger(), nullable=True, comment='시술 결과 입력 저장 여부'),
    sa.Column('note', sa.Text(), nullable=True, comment='특이사항'),
    sa.Column('first_recorded_at', sa.DateTime(), nullable=True, comment='최초 작성시간'),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True, comment='최종 수정시간'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment.id'], name=op.f('fk_treatment_session_treatment_id_treatment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatment_session'))
    )
    op.create_index(op.f('ix_treatment_session_id'), 'treatment_session', ['id'], unique=False)
    op.create_table('photo',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('treatment_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='nullable (회차에 속하지 않을 수도 있음)'),
    sa.Column('photo_type', sa.String(), nullable=True, comment='BEFORE | AFTER'),
    sa.Column('file_url', sa.String(length=255), nullable=True, comment='저장 경로'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['treatment_session.id'], name=op.f('fk_photo_session_id_treatment_session')),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment.id'], name=op.f('fk_photo_treatment_id_treatment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo'))
    )
    op.create_index(op.f('ix_photo_id'), 'photo', ['id'], unique=False)
    op.create_table('skin_color_measurement',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('region_type', sa.String(), nullable=True, comment='NORMAL | LESION'),
    sa.Column('l_value', sa.Float(), nullable=True, comment='L 값'),
    sa.Column('a_value', sa.Float(), nullable=True, comment='a 값'),
    sa.Column('b_value', sa.Float(), nullable=True, comment='b 값'),
    sa.Column('measurement_point', sa.String(length=255), nullable=True, comment='측정 위치(선택적)'),
    sa.Column('measured_at', sa.DateTime(), nullable=True, comment='측정 시각'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['treatment_session.id'], name=op.f('fk_skin_color_measurement_session_id_treatment_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skin_color_measurement'))
    )
    op.create_index(op.f('ix_skin_color_measurement_id'), 'skin_color_measurement', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skin_color_measurement_id'), table_name='skin_color_measurement')
    op.drop_table('skin_color_measurement')
    op.drop_index(op.f('ix_photo_id'), table_name='photo')
    op.drop_table('photo')
    op.drop_index(op.f('ix_treatment_session_id'), table_name='treatment_session')
    op.drop_table('treatment_session')
    op.drop_index(op.f('ix_treatment_id'), table_name='treatment')
    op.drop_table('treatment')
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_token_hash'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_session_id'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_id'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_expires_at'), table_name='user_tokens')
    op.drop_table('user_tokens')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shop_id'), table_name='shop')
    op.drop_table('shop')
    # ### end Alembic commands ###
