"""Refactor treatment images storage

Revision ID: 68675f0d6ca9
Revises: 8a528619101a
Create Date: 2025-11-12 07:10:58.017912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68675f0d6ca9'
down_revision = '8a528619101a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_id'), table_name='photo')
    op.drop_table('photo')
    op.add_column('treatment_session_image', sa.Column('session_id', sa.BigInteger(), nullable=False))
    op.drop_constraint(op.f('uq_treatment_session_image_sequence'), 'treatment_session_image', type_='unique')
    op.create_unique_constraint('uq_treatment_session_image_sequence', 'treatment_session_image', ['session_id', 'sequence_no'])
    op.drop_constraint(op.f('fk_treatment_session_image_treatment_session_id_treatme_f5e5'), 'treatment_session_image', type_='foreignkey')
    op.create_foreign_key(op.f('fk_treatment_session_image_session_id_treatment_session'), 'treatment_session_image', 'treatment_session', ['session_id'], ['id'])
    op.drop_column('treatment_session_image', 'treatment_session_id')
    op.drop_constraint(op.f('fk_uploaded_image_shop_id_shop'), 'uploaded_image', type_='foreignkey')
    op.drop_column('uploaded_image', 'shop_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_image', sa.Column('shop_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_uploaded_image_shop_id_shop'), 'uploaded_image', 'shop', ['shop_id'], ['id'])
    op.add_column('treatment_session_image', sa.Column('treatment_session_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_treatment_session_image_session_id_treatment_session'), 'treatment_session_image', type_='foreignkey')
    op.create_foreign_key(op.f('fk_treatment_session_image_treatment_session_id_treatme_f5e5'), 'treatment_session_image', 'treatment_session', ['treatment_session_id'], ['id'])
    op.drop_constraint('uq_treatment_session_image_sequence', 'treatment_session_image', type_='unique')
    op.create_unique_constraint(op.f('uq_treatment_session_image_sequence'), 'treatment_session_image', ['treatment_session_id', 'sequence_no'])
    op.drop_column('treatment_session_image', 'session_id')
    op.create_table('photo',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('treatment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='nullable (회차에 속하지 않을 수도 있음)'),
    sa.Column('photo_type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='BEFORE | AFTER'),
    sa.Column('file_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='저장 경로'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['treatment_session.id'], name=op.f('fk_photo_session_id_treatment_session')),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment.id'], name=op.f('fk_photo_treatment_id_treatment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo'))
    )
    op.create_index(op.f('ix_photo_id'), 'photo', ['id'], unique=False)
    # ### end Alembic commands ###

