"""Add uploaded_image and treatment_session_image tables

Revision ID: 8a528619101a
Revises: 03486deed5aa
Create Date: 2025-11-12 06:19:02.488233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a528619101a'
down_revision = '03486deed5aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_image',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.BigInteger(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('public_url', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('storage_backend', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name=op.f('fk_uploaded_image_shop_id_shop')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_image')),
    sa.UniqueConstraint('storage_path', name=op.f('uq_uploaded_image_storage_path'))
    )
    op.create_index(op.f('ix_uploaded_image_id'), 'uploaded_image', ['id'], unique=False)
    op.create_table('treatment_session_image',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('treatment_id', sa.BigInteger(), nullable=False),
    sa.Column('treatment_session_id', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_image_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('photo_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment.id'], name=op.f('fk_treatment_session_image_treatment_id_treatment')),
    sa.ForeignKeyConstraint(['treatment_session_id'], ['treatment_session.id'], name=op.f('fk_treatment_session_image_treatment_session_id_treatment_session')),
    sa.ForeignKeyConstraint(['uploaded_image_id'], ['uploaded_image.id'], name=op.f('fk_treatment_session_image_uploaded_image_id_uploaded_image')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatment_session_image')),
    sa.UniqueConstraint('treatment_session_id', 'sequence_no', name='uq_treatment_session_image_sequence')
    )
    op.create_index(op.f('ix_treatment_session_image_id'), 'treatment_session_image', ['id'], unique=False)
    op.create_unique_constraint('uq_customer_shop_phone_name', 'customer', ['shop_id', 'phone', 'name'])
    op.alter_column('treatment', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='시술명',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('treatment', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='시술명',
               existing_nullable=True)
    op.drop_constraint('uq_customer_shop_phone_name', 'customer', type_='unique')
    op.drop_index(op.f('ix_treatment_session_image_id'), table_name='treatment_session_image')
    op.drop_table('treatment_session_image')
    op.drop_index(op.f('ix_uploaded_image_id'), table_name='uploaded_image')
    op.drop_table('uploaded_image')
    # ### end Alembic commands ###

