"""add_photo_type_to_treatment_session_image

Revision ID: 9bd7b1c508ed
Revises: 799358ba1e35
Create Date: 2025-11-13 10:10:54.487982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bd7b1c508ed'
down_revision = '799358ba1e35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_id'), table_name='photo')
    op.drop_table('photo')
    op.create_unique_constraint('uq_customer_shop_phone_name', 'customer', ['shop_id', 'phone', 'name'])
    op.alter_column('treatment', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='시술명',
               existing_nullable=True)
    op.add_column('treatment_session_image', sa.Column('photo_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_session_image', 'photo_type')
    op.alter_column('treatment', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='시술명',
               existing_nullable=True)
    op.drop_constraint('uq_customer_shop_phone_name', 'customer', type_='unique')
    op.create_table('photo',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('treatment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='nullable (회차에 속하지 않을 수도 있음)'),
    sa.Column('photo_type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='BEFORE | AFTER'),
    sa.Column('file_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='저장 경로'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['treatment_session.id'], name=op.f('fk_photo_session_id_treatment_session')),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment.id'], name=op.f('fk_photo_treatment_id_treatment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo'))
    )
    op.create_index(op.f('ix_photo_id'), 'photo', ['id'], unique=False)
    # ### end Alembic commands ###

