"""add_unique_constraint_to_shop_email

Revision ID: b62450aa6630
Revises: 3e93f2a629b2
Create Date: 2025-11-06 23:41:40.966334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62450aa6630'
down_revision = '3e93f2a629b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photo', 'session_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_comment='nullable (회차에 속하지 않을 수도 있음)')
    # Create unique index for shop email
    op.create_index(op.f('ix_shop_email'), 'shop', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_email'), table_name='shop')
    op.alter_column('photo', 'session_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_comment='nullable (회차에 속하지 않을 수도 있음)')
    # ### end Alembic commands ###

