"""add sequence to treatment_session

Revision ID: f6e2737481ae
Revises: 9bd7b1c508ed
Create Date: 2025-11-14 14:29:35.996748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6e2737481ae'
down_revision = '9bd7b1c508ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # items table was already dropped, skip those operations
    # op.drop_index(op.f('ix_items_id'), table_name='items')
    # op.drop_table('items')
    
    # Check if sequence column already exists
    from sqlalchemy import inspect, text
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_columns = [c['name'] for c in inspector.get_columns('treatment_session')]
    
    if 'sequence' not in existing_columns:
        # Add sequence column as nullable first
        op.add_column('treatment_session', sa.Column('sequence', sa.Integer(), nullable=True, comment='회차 번호'))
        
        # Update existing rows: calculate sequence based on treatment_id and created_at
        # For each treatment, assign sequence numbers starting from 1
        
        # Get all treatment_ids that have sessions (including deleted ones)
        result = conn.execute(text("SELECT DISTINCT treatment_id FROM treatment_session"))
        treatment_ids = [row[0] for row in result]
        
        # For each treatment, assign sequence numbers
        for treatment_id in treatment_ids:
            # Get all sessions ordered by created_at (including deleted ones)
            sessions_result = conn.execute(
                text("""
                    SELECT id FROM treatment_session 
                    WHERE treatment_id = :treatment_id 
                    ORDER BY created_at ASC
                """),
                {"treatment_id": treatment_id}
            )
            sessions = [row[0] for row in sessions_result]
            
            # Assign sequence numbers
            for idx, session_id in enumerate(sessions, start=1):
                conn.execute(
                    text("UPDATE treatment_session SET sequence = :seq WHERE id = :id"),
                    {"seq": idx, "id": session_id}
                )
        
        # Commit the updates before making column NOT NULL
        conn.commit()
        
        # Now make the column NOT NULL
        op.alter_column('treatment_session', 'sequence', nullable=False)
    else:
        # Column already exists, just ensure it's NOT NULL if it isn't already
        # Check if there are any NULL values
        result = conn.execute(text("SELECT COUNT(*) FROM treatment_session WHERE sequence IS NULL"))
        null_count = result.scalar()
        
        if null_count > 0:
            # Update NULL values
            result = conn.execute(text("SELECT DISTINCT treatment_id FROM treatment_session WHERE sequence IS NULL"))
            treatment_ids = [row[0] for row in result]
            
            for treatment_id in treatment_ids:
                sessions_result = conn.execute(
                    text("""
                        SELECT id FROM treatment_session 
                        WHERE treatment_id = :treatment_id 
                        ORDER BY created_at ASC
                    """),
                    {"treatment_id": treatment_id}
                )
                sessions = [row[0] for row in sessions_result]
                
                for idx, session_id in enumerate(sessions, start=1):
                    conn.execute(
                        text("UPDATE treatment_session SET sequence = :seq WHERE id = :id AND sequence IS NULL"),
                        {"seq": idx, "id": session_id}
                    )
            conn.commit()
        
        # Check if column is nullable and make it NOT NULL if needed
        column_info = next((c for c in inspector.get_columns('treatment_session') if c['name'] == 'sequence'), None)
        if column_info and column_info['nullable']:
            op.alter_column('treatment_session', 'sequence', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_session', 'sequence')
    # items table recreation skipped as it was already dropped
    # ### end Alembic commands ###

